### ISSUE TITLE
Documentation is missing from the Win32Docs package for some APIs

### ISSUE THREAD

**Issue by mcooley** [microsoft/win32metadata#1419]
There are many APIs which are present in the metadata and are documented on learn.microsoft.com, but the documentation isn't included in the Microsoft.Windows.SDK.Win32Docs package.

Some examples (as of win32docs 0.1.12):

```[tasklist]
### Tasks
- [x] JetInit (MicrosoftDocs/win32)
- [x] MAPIInitIdle (https://github.com/MicrosoftDocs/office-developer-client-docs/tree/ff5646762963c1b28ab761a6e5a98b53c3193b6a/docs/outlook/mapi)
- [ ] CoInternetCombineUrl
- [x] AllocConsole (https://github.com/MicrosoftDocs/Console-Docs/tree/main/docs)
- [x] SQLGetCursorName (https://github.com/MicrosoftDocs/sql-docs/tree/41cf5b7c76915cf64b134ef583b800b015fa139b/docs/odbc/reference/syntax)
- [x] MrmCreateResourceIndexer (MicrosoftDocs/win32)
- [x] HcsCreateOperation (https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/f4bd609745bd109cc2821d0707783338f3ec30ff/virtualization/api/hcs/Reference)
```

(I wrote [a script](https://gist.github.com/mcooley/3f1cf4e59b3cbf6ab510f77105357d94) to get an initial list of these APIs.)

It looks like win32metadata would need to add additional documentation repos beyond MicrosoftDocs/sdk-api to resolve this.

**Comment by mikebattista** [comment]
The latest Win32Docs package has these APIs now minus CoInternetCombineUrl.
