### ISSUE TITLE
Add missing opaque handles and remove empty structs

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#1547]
See https://github.com/microsoft/wdkmetadata/issues/31.

- [ ] ?Windows.Win32.Data.HtmlHelp.IITGroup
- [ ] ?Windows.Win32.Data.HtmlHelp.IITQuery
- [ ] ?Windows.Win32.Data.HtmlHelp.IITStopWordList
- [x] Windows.Win32.Devices.AllJoyn._alljoyn_abouticon_handle
- [x] Windows.Win32.Devices.AllJoyn._alljoyn_abouticonobj_handle
- [x] Windows.Win32.Devices.AllJoyn._alljoyn_abouticonproxy_handle
- [x] Windows.Win32.Devices.BiometricFramework._WINIBIO_ENGINE_CONTEXT
- [x] Windows.Win32.Devices.BiometricFramework._WINIBIO_SENSOR_CONTEXT
- [x] Windows.Win32.Devices.BiometricFramework._WINIBIO_STORAGE_CONTEXT
- [x] Windows.Win32.Devices.HumanInterfaceDevice._HIDP_PREPARSED_DATA
- [x] Windows.Win32.Globalization.UBiDi
- [x] Windows.Win32.Globalization.UBiDiTransform
- [x] Windows.Win32.Globalization.UBreakIterator
- [x] Windows.Win32.Globalization.UCaseMap
- [x] Windows.Win32.Globalization.UCharsetDetector
- [x] Windows.Win32.Globalization.UCharsetMatch
- [x] Windows.Win32.Globalization.UCollationElements
- [x] Windows.Win32.Globalization.UCollator
- [x] Windows.Win32.Globalization.UConstrainedFieldPosition
- [x] Windows.Win32.Globalization.UConverter
- [x] Windows.Win32.Globalization.UConverterSelector
- [x] Windows.Win32.Globalization.UCPMap
- [x] Windows.Win32.Globalization.UDateFormatSymbols
- [x] Windows.Win32.Globalization.UDateIntervalFormat
- [x] Windows.Win32.Globalization.UEnumeration
- [x] Windows.Win32.Globalization.UFieldPositionIterator
- [x] Windows.Win32.Globalization.UFormattedDateInterval
- [x] Windows.Win32.Globalization.UFormattedList
- [x] Windows.Win32.Globalization.UFormattedNumber
- [x] Windows.Win32.Globalization.UFormattedNumberRange
- [x] Windows.Win32.Globalization.UFormattedRelativeDateTime
- [x] Windows.Win32.Globalization.UFormattedValue
- [x] Windows.Win32.Globalization.UGenderInfo
- [x] Windows.Win32.Globalization.UHashtable
- [x] Windows.Win32.Globalization.UIDNA
- [x] Windows.Win32.Globalization.UListFormatter
- [x] Windows.Win32.Globalization.ULocaleData
- [x] Windows.Win32.Globalization.ULocaleDisplayNames
- [x] Windows.Win32.Globalization.UMutableCPTrie
- [x] Windows.Win32.Globalization.UNormalizer2
- [x] Windows.Win32.Globalization.UNumberFormatter
- [x] Windows.Win32.Globalization.UNumberingSystem
- [x] Windows.Win32.Globalization.UPluralRules
- [x] Windows.Win32.Globalization.URegion
- [x] Windows.Win32.Globalization.URegularExpression
- [x] Windows.Win32.Globalization.URelativeDateTimeFormatter
- [x] Windows.Win32.Globalization.UResourceBundle
- [x] Windows.Win32.Globalization.USearch
- [x] Windows.Win32.Globalization.USet
- [x] Windows.Win32.Globalization.USpoofChecker
- [x] Windows.Win32.Globalization.USpoofCheckResult
- [x] Windows.Win32.Globalization.UStringPrepProfile
- [x] Windows.Win32.Globalization.UStringSearch
- [ ] ?Windows.Win32.Graphics.Direct3D11.CD3D11_VIDEO_DEFAULT
- [x] Windows.Win32.Graphics.DirectDraw._DD_DESTROYDRIVERDATA
- [x] Windows.Win32.Graphics.DirectDraw._DD_GETVPORTAUTOFLIPSURFACEDATA
- [x] Windows.Win32.Graphics.DirectDraw._DD_SETMODEDATA
- [x] Windows.Win32.Graphics.DirectDraw._DDFXROP
- [x] Windows.Win32.Graphics.OpenGL.GLUnurbs
- [x] Windows.Win32.Graphics.OpenGL.GLUquadric
- [x] Windows.Win32.Graphics.OpenGL.GLUtesselator
- [x] Windows.Win32.Media.KernelStreaming.IKsAllocator #1548 
- [x] Windows.Win32.Media.KernelStreaming.IKsAllocatorEx #1548 
- [x] Windows.Win32.Media.KernelStreaming.IKsPin #1548 
- [x] Windows.Win32.Networking.Clustering._HCHANGE
- [x] Windows.Win32.Networking.Clustering._HCLUSCRYPTPROVIDER
- [x] Windows.Win32.Networking.Clustering._HCLUSENUM
- [x] Windows.Win32.Networking.Clustering._HCLUSENUMEX
- [x] Windows.Win32.Networking.Clustering._HCLUSTER
- [x] Windows.Win32.Networking.Clustering._HGROUP
- [x] Windows.Win32.Networking.Clustering._HGROUPENUM
- [x] Windows.Win32.Networking.Clustering._HGROUPENUMEX
- [x] Windows.Win32.Networking.Clustering._HGROUPSET
- [x] Windows.Win32.Networking.Clustering._HGROUPSETENUM
- [x] Windows.Win32.Networking.Clustering._HNETINTERFACE
- [x] Windows.Win32.Networking.Clustering._HNETINTERFACEENUM
- [x] Windows.Win32.Networking.Clustering._HNETWORK
- [x] Windows.Win32.Networking.Clustering._HNETWORKENUM
- [x] Windows.Win32.Networking.Clustering._HNODE
- [x] Windows.Win32.Networking.Clustering._HNODEENUM
- [x] Windows.Win32.Networking.Clustering._HNODEENUMEX
- [x] Windows.Win32.Networking.Clustering._HREGBATCH
- [x] Windows.Win32.Networking.Clustering._HREGBATCHNOTIFICATION
- [x] Windows.Win32.Networking.Clustering._HREGBATCHPORT
- [x] Windows.Win32.Networking.Clustering._HREGREADBATCH
- [x] Windows.Win32.Networking.Clustering._HREGREADBATCHREPLY
- [x] Windows.Win32.Networking.Clustering._HRESENUM
- [x] Windows.Win32.Networking.Clustering._HRESENUMEX
- [x] Windows.Win32.Networking.Clustering._HRESOURCE
- [x] Windows.Win32.Networking.Clustering._HRESTYPEENUM
- [x] Windows.Win32.Networking.Ldap.LDAPSearch
- [x] Windows.Win32.Networking.WindowsWebServices.WS_CHANNEL
- [x] Windows.Win32.Networking.WindowsWebServices.WS_ERROR
- [x] Windows.Win32.Networking.WindowsWebServices.WS_HEAP
- [x] Windows.Win32.Networking.WindowsWebServices.WS_LISTENER
- [x] Windows.Win32.Networking.WindowsWebServices.WS_MESSAGE
- [x] Windows.Win32.Networking.WindowsWebServices.WS_METADATA
- [x] Windows.Win32.Networking.WindowsWebServices.WS_OPERATION_CONTEXT
- [x] Windows.Win32.Networking.WindowsWebServices.WS_POLICY
- [x] Windows.Win32.Networking.WindowsWebServices.WS_SECURITY_CONTEXT
- [x] Windows.Win32.Networking.WindowsWebServices.WS_SECURITY_TOKEN
- [x] Windows.Win32.Networking.WindowsWebServices.WS_SERVICE_HOST
- [x] Windows.Win32.Networking.WindowsWebServices.WS_SERVICE_PROXY
- [x] Windows.Win32.Networking.WindowsWebServices.WS_XML_BUFFER
- [x] Windows.Win32.Networking.WindowsWebServices.WS_XML_READER
- [x] Windows.Win32.Networking.WindowsWebServices.WS_XML_WRITER
- [x] Windows.Win32.Networking.WinSock.RIO_BUFFERID_t
- [x] Windows.Win32.Networking.WinSock.RIO_CQ_t
- [x] Windows.Win32.Networking.WinSock.RIO_RQ_t
- [x] Windows.Win32.NetworkManagement.Dhcp.DHCP_CLIENT_SEARCH_UNION
- [x] Windows.Win32.NetworkManagement.Dhcp.DHCP_OPTION_ELEMENT_UNION
- [x] Windows.Win32.NetworkManagement.Dhcp.DHCP_OPTION_SCOPE_UNION6
- [x] Windows.Win32.NetworkManagement.Dhcp.DHCP_SUBNET_ELEMENT_UNION
- [x] Windows.Win32.NetworkManagement.Dhcp.DHCP_SUBNET_ELEMENT_UNION_V4
- [x] Windows.Win32.NetworkManagement.Dhcp.DHCP_SUBNET_ELEMENT_UNION_V6
- [x] Windows.Win32.Security.Authentication.Identity._HMAPPER
- [x] Windows.Win32.Storage.Imapi._MSGSESS
- [x] Windows.Win32.Storage.IscsiDisc._ADAPTER_OBJECT
- [ ] ?Windows.Win32.Storage.Vss.IVssExamineWriterMetadata (C++ class)
- [x] Windows.Win32.System.AddressBook._WABACTIONITEM
- [x] Windows.Win32.System.Com.IContext
- [x] Windows.Win32.System.Com.IEnumContextProps
- [ ] ?Windows.Win32.System.Com.StructuredStorage.PMemoryAllocator (C++ class)
- [x] Windows.Win32.System.Iis._IIS_CRYPTO_BLOB
- [x] Windows.Win32.System.RemoteManagement.WSMAN_API
- [x] Windows.Win32.System.RemoteManagement.WSMAN_COMMAND
- [x] Windows.Win32.System.RemoteManagement.WSMAN_OPERATION
- [x] Windows.Win32.System.RemoteManagement.WSMAN_SESSION
- [x] Windows.Win32.System.RemoteManagement.WSMAN_SHELL
- [x] Windows.Win32.System.Rpc._NDR_ASYNC_MESSAGE
- [x] Windows.Win32.System.Rpc._NDR_CORRELATION_INFO
- [x] Windows.Win32.System.Rpc._NDR_PROC_CONTEXT
- [x] Windows.Win32.System.Rpc.NDR_ALLOC_ALL_NODES_CONTEXT
- [x] Windows.Win32.System.Rpc.NDR_POINTER_QUEUE_STATE
- [x] Windows.Win32.System.Search.IRowsetExactScroll
- [x] Windows.Win32.System.Services._SC_NOTIFICATION_REGISTRATION
- [x] Windows.Win32.System.SystemServices.AtlThunkData_t
- [x] Windows.Win32.System.SystemServices.TEB
- [x] Windows.Win32.System.SystemServices.TP_CLEANUP_GROUP
- [x] Windows.Win32.System.SystemServices.TP_POOL
- [x] Windows.Win32.System.WindowsProgramming._D3DHAL_CALLBACKS https://github.com/microsoft/wdkmetadata/issues/34
- [x] Windows.Win32.System.WindowsProgramming._D3DHAL_GLOBALDRIVERDATA https://github.com/microsoft/wdkmetadata/issues/34
- [x] Windows.Win32.System.WinRT._RO_REGISTRATION_COOKIE
- [x] Windows.Win32.System.Wmi.MI_Module_Self
- [x] Windows.Win32.UI.Shell._APPCONSTRAIN_REGISTRATION
- [x] Windows.Win32.UI.Shell._APPSTATE_REGISTRATION
- [x] Windows.Win32.UI.Shell.PropertiesSystem.SERIALIZEDPROPSTORAGE
- [x] Windows.Win32.Web.InternetExplorer.HTMLPersistEvents
- [x] Windows.Win32.Web.InternetExplorer.LayoutRectEvents
- [x] Windows.Win32.Web.MsHtml.HostDialogHelper

**Comment by mikebattista** [comment]
[Added missing ICU opaque structs.](https://github.com/microsoft/win32metadata/commit/6d990b7edad83f954ae146c3f3daeea77aafe3ec)

[Added missing AllJoyn handles.](https://github.com/microsoft/win32metadata/commit/e32157758788f96c14f56b3212325d5161d7d4bf)

**Comment by mikebattista** [comment]
#632
