### ISSUE TITLE
Inconsistencies and missing entities in comparison with C++ and winapi-rs API

### ISSUE THREAD

**Issue by ancwrd1** [microsoft/win32metadata#720]
I've been porting some projects from winapi-rs and from C++ to windows-rs, here is the list of inconsistencies found so far. I thought it might be a good idea to report them here.

* [ ] #796
* [x]  `RegisterEventSourceW` returns `EventSourceHandle`, but `ReportEventW` accepts `HANDLE`.
* [x]  #587 Some string constants are absent from the crate, need to define them manually: `NCRYPT_NAME_PROPERTY`, `NCRYPT_PIN_PROPERTY`, `NCRYPT_PROVIDER_HANDLE_PROPERTY`, etc
* [x]  Absent `NCRYPT_HANDLE` (isize) and `HCERTSTORE` (*const c_void) types
* [x]  Absent digest and encryption algorithms OIDs, e.g. `OID_RSA_SHA256RSA`
* [ ] #1482
* [x]  #587 Absent `SPLDS_xxx` string constants
* [ ] #1481
* [x]  #587 Absent `TRUSTED_PUBLISHER`, `LOCALE_NAME_SYSTEM_DEFAULT` string constants
* [x]  #587 Absent `CERT_STORE_PROV_SYSTEM` (and similar) constant
* [x]  Absent `PRINTER_ALL_ACCESS` constant
* [x]  Many native APIs accept const strings but with PWSTR I am always forced to cast to *mut u16

**Comment by mikebattista** [comment]
> Many native APIs accept const strings but with PWSTR I am always forced to cast to *mut u16

Could you clarify what we could improve here?

**Comment by kennykerr** [comment]
> Many native APIs accept const strings but with PWSTR I am always forced to cast to *mut u16

This is Rust-specific and has already been handled by the `windows` crate. See https://github.com/microsoft/windows-rs/pull/1468 and https://github.com/microsoft/windows-rs/pull/1470

**Comment by mikebattista** [comment]
Thanks. I will mark it completed.
